### ISSUE TITLE
HOW DO I USE

### ISSUE THREAD

**Issue by regretings** [yrsegal/thicc-entities#8]
I have no idea how to use this mod, you need to make it more clear ,Help.

**Comment by yrsegal** [comment]
edit the config. It's meant for packmakers.

**Comment by regretings** [comment]
How do i edit the config though?

**Comment by German998** [comment]
if u read the desc you will know how. :/ 
"This mod provides a config which lets you change the scale, attack strength, speed, jump height, and such of nearly any living entity in the game.
The mod will generate a full list of defaulted config values. This mod won't change anything by default, until you change the config.
minecraft { player { D:armor=0.0 D:damage=0.0625 D:health=0.5 D:jump=0.5 D:reach=0.0625 D:scale=0.0625 D:speed=0.25 D:toughness=0.0 } }
As an example, this config will put the player to the size of chisels-and-bits, including their jump height and speed. "

https://hastebin.com/oqihuredek.pl

**Comment by Pirate81327** [comment]
I have the same problem. It keeps reverting to old settings in the client and there is no config file
When I open the mod file in notepad, it comes up as complete gibberish.
Sample: 
PK   ñ–™L           	  META-INF/þÊ   PK  ñ–™L               META-INF/MANIFEST.MFóMÌËLK-.Ñ
K-*ÎÌÏ³R0Ô3àåróõqÎ/J
È)MÏÌsÎÏ+IÌÌ+
úæ§X)”•¦¢)±R(Ï,J-NMOÌÑ+ÉÈLNÖK,ÎÕ±Šx¹x¹ PKMã …Y   p   PK   ñ–™L

**Comment by Pirate81327** [comment]
oh
i found the config file. It's in config folder in .minecraft for anyone also having this problem

**Comment by Pirate81327** [comment]
called thiccentities.cfg

**Comment by Opsagnik** [comment]
thx soo much bro
